### ISSUE TITLE
[FEATURE] Hide / Give CTA in empty sections

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap#18]
**Is your feature request related to a problem? Please describe.**
When data doesn't exist, the section looks empty.

**Describe the solution you'd like**
We should either hide or give a clear call to action (CTA) to the user.

**Describe alternatives you've considered**
<TODO: A clear and concise description of any alternative solutions or features you've considered.>

**Additional context**
![40227649-c42cd904-5a97-11e8-9961-1db0840830f7](https://user-images.githubusercontent.com/877919/43367120-d656bd4c-9350-11e8-9288-c50567e53f97.png)

**Comment by kilemensi** [comment]
Functionality already added to HURUmap.
